services:
    client:
        container_name: client
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - server
        networks:
            - web3
    server:
        container_name: server
        env_file:
            - path: ./backend/.env
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000"
        networks:
            - web3
        # restart: always
networks:
    web3:
        driver: bridge
